### ISSUE TITLE
Where to find the converted_particles.mcfunction file.

### ISSUE THREAD

**Issue by Chilipotpie** [AndreyFernandes-NP/Python-Particle-Converter#1]
After running it I don't understand where you have the new file set to be stored on the pc where do i find it?

**Comment by Chilipotpie** [comment]
On the off chance you see this I'd like to note that I was able to find that new file but the dust particles still don't work because the "1" values need to be switched to "1.0" to work in cases of mixed float and int variable types in the particle color values like:     
particle minecraft:dust{color:[1,0.98,1]}

**Comment by AndreyFernandes-NP** [comment]
Fixed in the newest version, but I would highly recommend using this fork from the original particle converter, it supports the new changes and it's something that I've attempted to do before but couldn't find the right script to update, so that's why I made this simple .py

Fork: https://github.com/fzlz-java/Particle-Converter-1.21.1
